#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18051
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MyTasque.Resource", IsApplication=true)]

namespace MyTasque
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			MyTasque.Lib.Resource.String.library_name = MyTasque.Resource.String.library_name;
			MyTasque.Backends.Resource.String.library_name = MyTasque.Resource.String.library_name;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int backendKeys = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int backendValues = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int orderByKeys = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int orderByValues = 2131099651;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Add = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Delete = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Edit = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Info = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int NoteBackground = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Save = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Settings = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080013
			public const int btAddNewNote = 2131230739;
			
			// aapt resource value: 0x7f08001a
			public const int btAddNewTask = 2131230746;
			
			// aapt resource value: 0x7f080009
			public const int btDeleteNote = 2131230729;
			
			// aapt resource value: 0x7f080014
			public const int btDeleteTask = 2131230740;
			
			// aapt resource value: 0x7f080018
			public const int cbDone = 2131230744;
			
			// aapt resource value: 0x7f08000b
			public const int cbTaskCompleted = 2131230731;
			
			// aapt resource value: 0x7f08000a
			public const int edTaskText = 2131230730;
			
			// aapt resource value: 0x7f080001
			public const int imageView1 = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int linearLayout1 = 2131230720;
			
			// aapt resource value: 0x7f080007
			public const int linearLayout2 = 2131230727;
			
			// aapt resource value: 0x7f08000c
			public const int linearLayout3 = 2131230732;
			
			// aapt resource value: 0x7f08000d
			public const int linearLayout4 = 2131230733;
			
			// aapt resource value: 0x7f08000f
			public const int linearLayout5 = 2131230735;
			
			// aapt resource value: 0x7f080012
			public const int lvNotes = 2131230738;
			
			// aapt resource value: 0x7f080019
			public const int lvTasks = 2131230745;
			
			// aapt resource value: 0x7f08001f
			public const int menuAbout = 2131230751;
			
			// aapt resource value: 0x7f08001b
			public const int menuAddTaskList = 2131230747;
			
			// aapt resource value: 0x7f08001c
			public const int menuChangeTaskListName = 2131230748;
			
			// aapt resource value: 0x7f08001e
			public const int menuDeleteTaskList = 2131230750;
			
			// aapt resource value: 0x7f08001d
			public const int menuSettings = 2131230749;
			
			// aapt resource value: 0x7f080020
			public const int menuTaskEditSave = 2131230752;
			
			// aapt resource value: 0x7f080006
			public const int pager = 2131230726;
			
			// aapt resource value: 0x7f080015
			public const int rlTask = 2131230741;
			
			// aapt resource value: 0x7f080002
			public const int textView1 = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int textView2 = 2131230723;
			
			// aapt resource value: 0x7f080005
			public const int textView3 = 2131230725;
			
			// aapt resource value: 0x7f080004
			public const int textView4 = 2131230724;
			
			// aapt resource value: 0x7f08000e
			public const int textView5 = 2131230734;
			
			// aapt resource value: 0x7f080017
			public const int tvDetail = 2131230743;
			
			// aapt resource value: 0x7f080016
			public const int tvHeading = 2131230742;
			
			// aapt resource value: 0x7f080008
			public const int tvNote = 2131230728;
			
			// aapt resource value: 0x7f080010
			public const int tvTaskDueDate = 2131230736;
			
			// aapt resource value: 0x7f080011
			public const int tvTaskDueTime = 2131230737;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int About = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int HomeScreen = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int NoteItem = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int TaskEditScreen = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int TaskItem = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int TaskList = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int ActionBar = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int ActionBarTaskEdit = 2131165185;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050019
			public const int AboutActivity = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int Author = 2131034138;
			
			// aapt resource value: 0x7f05001c
			public const int Date = 2131034140;
			
			// aapt resource value: 0x7f05003c
			public const int DummyBackend_BackendNotInitialized = 2131034172;
			
			// aapt resource value: 0x7f05003d
			public const int DummyBackend_DeleteTaskList_ListNotExists = 2131034173;
			
			// aapt resource value: 0x7f05001b
			public const int Institution = 2131034139;
			
			// aapt resource value: 0x7f05003e
			public const int LocalBackend_BackendNotInitialized = 2131034174;
			
			// aapt resource value: 0x7f05003f
			public const int LocalBackend_CreateTaskList_ListAlreadyExists = 2131034175;
			
			// aapt resource value: 0x7f050040
			public const int LocalBackend_DeleteTaskList_ListNotExists = 2131034176;
			
			// aapt resource value: 0x7f05003b
			public const int TaskEditActivity = 2131034171;
			
			// aapt resource value: 0x7f05003a
			public const int TasquePreferenceActivity = 2131034170;
			
			// aapt resource value: 0x7f050024
			public const int about = 2131034148;
			
			// aapt resource value: 0x7f050008
			public const int adEnterTaskListName = 2131034120;
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f05002b
			public const int backendCategoryTitle = 2131034155;
			
			// aapt resource value: 0x7f05002f
			public const int backendDefault = 2131034159;
			
			// aapt resource value: 0x7f050030
			public const int backendDialogTitle = 2131034160;
			
			// aapt resource value: 0x7f050031
			public const int backendTitle = 2131034161;
			
			// aapt resource value: 0x7f050003
			public const int btAdd = 2131034115;
			
			// aapt resource value: 0x7f050007
			public const int btCancel = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int btOk = 2131034118;
			
			// aapt resource value: 0x7f050020
			public const int changeTaskListName = 2131034144;
			
			// aapt resource value: 0x7f05000f
			public const int completed = 2131034127;
			
			// aapt resource value: 0x7f05001d
			public const int createNewTaskTitle = 2131034141;
			
			// aapt resource value: 0x7f050017
			public const int createNoteTitle = 2131034135;
			
			// aapt resource value: 0x7f05000a
			public const int deleteTaskListMessage = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int deleteTaskListTitle = 2131034121;
			
			// aapt resource value: 0x7f05000c
			public const int deleteTaskMessage = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int deleteTaskTitle = 2131034123;
			
			// aapt resource value: 0x7f050032
			public const int displayCategoryTitle = 2131034162;
			
			// aapt resource value: 0x7f050015
			public const int dueDate = 2131034133;
			
			// aapt resource value: 0x7f050004
			public const int dueOn = 2131034116;
			
			// aapt resource value: 0x7f050016
			public const int dueTime = 2131034134;
			
			// aapt resource value: 0x7f050010
			public const int edNewNoteHint = 2131034128;
			
			// aapt resource value: 0x7f050002
			public const int edNewTaskHint = 2131034114;
			
			// aapt resource value: 0x7f050018
			public const int editNoteTitle = 2131034136;
			
			// aapt resource value: 0x7f05002c
			public const int infoCategoryTitle = 2131034156;
			
			// aapt resource value: 0x7f050000
			public const int library_name = 2131034112;
			
			// aapt resource value: 0x7f050021
			public const int menuAddTaskList = 2131034145;
			
			// aapt resource value: 0x7f050023
			public const int menuChangeTaskListName = 2131034147;
			
			// aapt resource value: 0x7f050022
			public const int menuDeleteTaskList = 2131034146;
			
			// aapt resource value: 0x7f05001e
			public const int note = 2131034142;
			
			// aapt resource value: 0x7f05000e
			public const int notes = 2131034126;
			
			// aapt resource value: 0x7f05000d
			public const int nothingSelected = 2131034125;
			
			// aapt resource value: 0x7f050033
			public const int orderByDefault = 2131034163;
			
			// aapt resource value: 0x7f050034
			public const int orderByDialogTitle = 2131034164;
			
			// aapt resource value: 0x7f050035
			public const int orderByTitle = 2131034165;
			
			// aapt resource value: 0x7f050028
			public const int password = 2131034152;
			
			// aapt resource value: 0x7f05002a
			public const int passwordDialogTitle = 2131034154;
			
			// aapt resource value: 0x7f050029
			public const int passwordSummary = 2131034153;
			
			// aapt resource value: 0x7f050005
			public const int save = 2131034117;
			
			// aapt resource value: 0x7f05001f
			public const int settings = 2131034143;
			
			// aapt resource value: 0x7f050038
			public const int showActive = 2131034168;
			
			// aapt resource value: 0x7f050039
			public const int showActiveSummary = 2131034169;
			
			// aapt resource value: 0x7f050036
			public const int showCompleted = 2131034166;
			
			// aapt resource value: 0x7f050037
			public const int showCompletedSummary = 2131034167;
			
			// aapt resource value: 0x7f050012
			public const int taskCompleted = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int taskDueOn = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int taskNameCannotBeEmpty = 2131034132;
			
			// aapt resource value: 0x7f050011
			public const int taskText = 2131034129;
			
			// aapt resource value: 0x7f05002e
			public const int tasqueInternetSummary = 2131034158;
			
			// aapt resource value: 0x7f05002d
			public const int tasqueInternetTitle = 2131034157;
			
			// aapt resource value: 0x7f050025
			public const int username = 2131034149;
			
			// aapt resource value: 0x7f050027
			public const int usernameDialogTitle = 2131034151;
			
			// aapt resource value: 0x7f050026
			public const int usernameSummary = 2131034150;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int preferences = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
